;
; CIA Registers
;

CIA1_PRA        = $DC00
CIA1_PRB        = $DC01
CIA1_DDRA       = $DC02
CIA1_DDRB       = $DC03
CIA1_TA_LO      = $DC04
CIA1_TA_HI      = $DC05
CIA1_TB_LO      = $DC06
CIA1_TB_HI      = $DC07
CIA1_TOD_10THS  = $DC08
CIA1_TOD_SEC    = $DC09
CIA1_TOD_MIN    = $DC0A
CIA1_TOD_HR     = $DC0B
CIA1_SDR        = $DC0C
CIA1_ICR        = $DC0D
CIA1_CRA        = $DC0E
CIA1_CRB        = $DC0F

CIA2_PRA        = $DD00
CIA2_PRB        = $DD01
CIA2_DDRA       = $DD02
CIA2_DDRB       = $DD03
CIA2_TA_LO      = $DD04
CIA2_TA_HI      = $DD05
CIA2_TB_LO      = $DD06
CIA2_TB_HI      = $DD07
CIA2_TOD_10THS  = $DD08
CIA2_TOD_SEC    = $DD09
CIA2_TOD_MIN    = $DD0A
CIA2_TOD_HR     = $DD0B
CIA2_SDR        = $DD0C
CIA2_ICR        = $DD0D
CIA2_CRA        = $DD0E
CIA2_CRB        = $DD0F

; vim: ft=asm:et:si:ts=8:sts=8:sw=8
