.import	inst_ad
.import	inst_sr
.import	inst_wt
.import	inst_pt
.import	inst_ft
.import inst_vdelay
.import inst_vcount
.import inst_voff
.import wave_l
.import wave_h
.import pulse_l
.import pulse_h
.import flt8580_l
.import	flt8580_h
.import flt6581_l
.import	flt6581_h
.import sfx_ad
.import sfx_sr
.import sfx_wt
.import sfx_pt
.import sfx_ft
.import sfx_pitch

; vim: ft=asm:et:si:ts=8:sts=8:sw=8
