KRNL_LISTEN	= $ffb1
KRNL_SECOND     = $ff93
KRNL_UNLSN      = $ffae
KRNL_ACPTR      = $ffa5
KRNL_CHKIN      = $ffc6
KRNL_CHRIN      = $ffcf
KRNL_CHROUT     = $ffd2
KRNL_CIOUT      = $ffa8
KRNL_CLOSE      = $ffc3
KRNL_OPEN       = $ffc0
KRNL_SETMSG     = $ff90
KRNL_SETNAM     = $ffbd
KRNL_SETLFS     = $ffba
KRNL_CLRCHN     = $ffcc
KRNL_GETIN      = $ffe4
KRNL_LOAD       = $ffd5
KRNL_SAVE       = $ffd8

KRNL_GETKB      = $f142
KRNL_RESETIO    = $fda3

; vim: ft=asm:et:si:ts=8:sts=8:sw=8
