; map uc characters to the correct position in lc petscii table
.charmap        $41, $61
.charmap        $42, $62
.charmap        $43, $63
.charmap        $44, $64
.charmap        $45, $65
.charmap        $46, $66
.charmap        $47, $67
.charmap        $48, $68
.charmap        $49, $69
.charmap        $4a, $6a
.charmap        $4b, $6b
.charmap        $4c, $6c
.charmap        $4d, $6d
.charmap        $4e, $6e
.charmap        $4f, $6f
.charmap        $50, $70
.charmap        $51, $71
.charmap        $52, $72
.charmap        $53, $73
.charmap        $54, $74
.charmap        $55, $75
.charmap        $56, $76
.charmap        $57, $77
.charmap        $58, $78
.charmap        $59, $79
.charmap        $5a, $7a

; keep ` in standard location
.charmap        $60, $60

; vim: ft=asm:et:si:ts=8:sts=8:sw=8
