;
; VIA Registers
;

VIA1_PRB        = $1800
VIA1_PRA        = $1801
VIA1_DDRB       = $1802
VIA1_DDRA       = $1803
VIA1_T1C_L      = $1804
VIA1_T1C_H      = $1805
VIA1_T1L_L      = $1806
VIA1_T1L_H      = $1807
VIA1_T2C_L      = $1808
VIA1_T2C_H      = $1809
VIA1_SR         = $180A
VIA1_ACR        = $180B
VIA1_PCR        = $180C
VIA1_IFR        = $180D
VIA1_IER        = $180E

VIA2_PRB        = $1C00
VIA2_PRA        = $1C01
VIA2_DDRB       = $1C02
VIA2_DDRA       = $1C03
VIA2_T1C_L      = $1C04
VIA2_T1C_H      = $1C05
VIA2_T1L_L      = $1C06
VIA2_T1L_H      = $1C07
VIA2_T2C_L      = $1C08
VIA2_T2C_H      = $1C09
VIA2_SR         = $1C0A
VIA2_ACR        = $1C0B
VIA2_PCR        = $1C0C
VIA2_IFR        = $1C0D
VIA2_IER        = $1C0E

; vim: ft=asm:et:si:ts=8:sts=8:sw=8
